### ISSUE TITLE
Twitter functionality

### ISSUE THREAD

**Issue by joeflack4** [TB-Modeling/modeltb.org#10]
## Description
Integrate Twitter w/ the website.

## Steps
- [ ] 1. **Account**: Create and/or choose 1+ of our team's Twitter accounts to integrate w/ the website.
- [ ] 2. **Brainstorm**: Where/how do we want to integrate? _(@ddowdy I think we'll need to have some further discussion on this at our check-in or otherwise to determine what we want to add)_
- [ ] 3. **Research**: Determine the best means, e.g. 1 or more WordPress plugins.
- [ ] 4. **Execute**: Add feature.

**Comment by joeflack4** [comment]
@ddowdy If you have any ideas here, feel free to comment.

**Comment by ddowdy** [comment]
I think we should set up a team twitter account, have the management of that account rotate between interested members, and link that account to the website. We can discuss later today!

**Comment by joeflack4** [comment]
David's twitter page has been added as a link to the 'twitter' widget on the contact page: https://modeltb.wordpress.com/contact/
